- name: Demo on variables 
  hosts: jumpbox
  vars:
    URL: play.example.com 
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: Hello - {{URL}}

- name: Demo on variables - using file 
  hosts: jumpbox
  vars_files:
    - sample-vars.yml  
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: Hello - {{URL}}      

- name: Demo on variables - task 
  hosts: jumpbox
  tasks:
  - name: Print message
    vars:
      URL: task.example.com  
    ansible.builtin.debug:
      msg: Hello - {{URL}}   
     
- name: Demo on variables - inventory-file
  hosts: jumpbox
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: Hello - {{URL}}   


- name: Demo on facts/pre-defined variables
  hosts: jumpbox
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: My name is - {{ansible_hostname}}
      msg: My IP is - {{ansible_all_ipv4_addresses}}  

