- name: Demo on loops
  hosts: jumpbox 
  tasks:
  - ansible.builtin.debug:
      msg: I am eating - {{item}}
    loop: 
      - apple 
      - orange 
      - pineapple
  tasks:      
  - name: Using dict2items
    ansible.builtin.debug:
      msg: I have {{ item.quantity }} {{ item.name }}
    loop: 
      - {name: apple, quantity: 10}
      - {name: orange, quantity: 20}
      - {name: pineapple, quantity: 30}
   


  

